# -*- coding: utf-8 -*-
{
    'name': "Applicant Tracking System",

    'summary': """
        Inherit module for HR Recruitment to includes all required fields for Applicant Tracking System (ATS)""",

    'description': """
        This module inherit hr_recruitment module to add all required fields for ATS, including Project Management and Deployment Module on HRMS System
    """,

    'author': "Abdul Aziz Yaakup",
    'website': "http://optivolve.com",
    'category': 'Employees',
    'version': '1.0',
    'depends': ['base','hr_recruitment','hr','hr_contract','website','sign','web_google_maps','sms_pushbullet','whatsapp_wassenger','op_scanner'],

    'data': [
        'security/ir.model.access.csv',
        'data/delete_existing_stage_data.xml',
        'data/ats_website_data.xml',
        'data/main_stage_data.xml',
        'data/applicant_races_data.xml',
        'data/days_available_data.xml',
        'data/contact_substage_data.xml',
        'data/application_substage_data.xml',
        'data/interview_substage_data.xml',
        'data/employment_offer_substage_data.xml',
        'data/job_position_data.xml',
        'data/job_source_data.xml',
        'data/character_traits_data.xml',
        'data/map_website_data.xml',
        'data/preferred_location_data.xml',
        'data/preferred_site_data.xml',
        'data/salary_package_data.xml',
        'views/ov_ats_project_site_views.xml',
        'wizard/ov_ats_custom_activity_wizard_views.xml',
        'wizard/ov_ats_gothere_wizard_views.xml',
        'wizard/ov_ats_site_location_map_wizard_views.xml',
        'wizard/ov_ats_employee_resign_wizard_views.xml',
        'wizard/ov_ats_applicant_blacklist_wizard_views.xml',
        'wizard/ov_ats_applicant_banned_wizard_views.xml',
        'views/ov_ats_views.xml',
        'views/ov_ats_employee_views.xml',
        'views/ov_ats_sequence_views.xml',
        'views/ov_ats_days_avail_views.xml',
        'views/ov_ats_custom_activity_views.xml',
        'views/ov_ats_other_views.xml',
        'views/ov_ats_substage_views.xml',
        'views/ov_ats_educational_views.xml',
        'views/ov_ats_friend_relative_views.xml',
        'views/ov_ats_languages_views.xml',
        'views/ov_ats_career_history_views.xml',
        'views/ov_ats_character_traits_views.xml',
        'views/ov_ats_map_website_views.xml',
        'views/ov_ats_res_users_views.xml',
        'views/interview_form.xml',
        'views/application_form.xml',
        'views/contract_daily.xml',
        'views/contract_monthly.xml',
        'views/emp_contract_daily.xml',
        'views/emp_contract_monthly.xml',
        'views/ov_ats_application_templates.xml',
    ],
    
    'demo': [],
    'qweb': ['static/src/xml/activity.xml',
             # 'static/src/xml/systray.xml',
             ],
    'installabe':True,
}