# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Project CRM',
    'version': '1.0',
    'category': 'Sales/CRM',
    'sequence': 15,
    'summary': 'Project as a parent for leads and opportunities',
    'description': "",
    'website': 'https://www.odoo.com',
    'depends': [
        'crm',
        'sale_crm',
        'starken-crm',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/master_project.xml',
        'data/chg_project_crm_sequence.xml',
        'wizard/create_non_bci_wizard_master_views.xml',
        'wizard/chg_project_crm_lead_views.xml',
        'wizard/chg_project_crm_lead_views2.xml',
        'wizard/chg_project_crm_lead_check_duplicate_views.xml',
        'wizard/chg_project_crm_lead_assign_to_views.xml',
        'wizard/chg_master_project_filter.xml',
        'wizard/chg_bci_project_filter.xml',
        'wizard/chg_master_project_filter_from_lead.xml',
        'wizard/search_and_create_bci_project_view.xml',
        'wizard/create_sub_leads.xml',
        'wizard/create_non_bci_views.xml',
        'wizard/action_reject_project.xml',
        'wizard/drymix_create_sub_lead.xml',
        'wizard/signature_create_sub_lead.xml',
        'wizard/crm_midah_report.xml',
        'views/crm_bu_plant.xml',
        'views/chg_project_crm_views.xml',
        'views/chg_master_project_views.xml',
        'views/chg_project_crm_category_views.xml',
        'views/chg_project_crm_keywords_views.xml',
        'views/chg_project_crm_status_views.xml',
        'views/chg_project_crm_stage_views.xml',
        'views/chg_crm_project_owner_type_views.xml',
        'views/chg_crm_project_dev_type_views.xml',
        'views/chg_crm_bu_projects_views.xml',
        'views/chg_leads.xml',
        'views/chg_res_partner_types_views.xml',
        'views/chg_res_partner_views.xml',
        'views/chg_res_company_views.xml',
        # 'views/master_view.xml',

    ],
    'demo': [
    ],
    'css': [],
    'installable': True,
    'application': True,
    'auto_install': False
}
